# Generated by Django 3.0.7 on 2020-06-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=126)),
                ('last_name', models.CharField(max_length=126)),
                ('email', models.EmailField(max_length=260, unique=True)),
            ],
        ),
    ]
